"use client";

import { useState } from "react";
import { Icon } from "@iconify/react";
import Tabs from "./group/Tabs";
import Select from "./Select";
import ColorPickerPopup from "./ColorPickerPopup";
import BoxShadow from "./BoxShadow";
import Dimensions from "./Dimensions";
import NumberControl from "./Number";

/**
 * Border control — Normal / Hover tabs.
 *
 * Schema shape:
 * {
 *   normal: {
 *     type   : "" | "none" | "solid" | "double" | "dotted" | "dashed" | "groove"
 *     width  : { top, right, bottom, left, unit }   (4-sided, px only)
 *     color  : string
 *     radius : { top, right, bottom, left, unit }   (4-sided, px / % / em / rem)
 *   },
 *   hover: { ...same... },
 *   boxShadow: { normal: {...}, hover: {...}, transition: number },
 *   transition: number  (ms)
 * }
 *
 * CSS is generated by cssRegistry["border"] in css.ts.
 */

// ─── constants ────────────────────────────────────────────────────────────────

const BORDER_TYPES = [
    { value: "", label: "Default" },
    { value: "none", label: "None" },
    { value: "solid", label: "Solid" },
    { value: "double", label: "Double" },
    { value: "dotted", label: "Dotted" },
    { value: "dashed", label: "Dashed" },
    { value: "groove", label: "Groove" },
];

const WIDTH_UNITS = ["px", "%", "em", "rem"] as const;
const RADIUS_UNITS = ["px", "%", "em", "rem"] as const;

// ─── defaults ─────────────────────────────────────────────────────────────────

const DEFAULT_WIDTH = { top: 0, right: 0, bottom: 0, left: 0, unit: "px" };
const DEFAULT_RADIUS = { top: 0, right: 0, bottom: 0, left: 0, unit: "px" };

const DEFAULT_SIDE_STATE = {
    type: "" as string,
    width: DEFAULT_WIDTH,
    color: "#000000",
    radius: DEFAULT_RADIUS,
};

const DEFAULT_BOX_SHADOW = {
    normal: { x: 0, y: 0, blur: 0, spread: 0, color: "rgba(0,0,0,0.15)", inset: false },
    hover: { x: 0, y: 0, blur: 0, spread: 0, color: "rgba(0,0,0,0.15)", inset: false },
    transition: 300,
};

function normalizeSide(raw: any) {
    // Migrate legacy flat width (number) → 4-sided object
    const rawWidth = raw?.width;
    const width =
        rawWidth === undefined || rawWidth === null
            ? DEFAULT_WIDTH
            : typeof rawWidth === "number"
                ? { top: rawWidth, right: rawWidth, bottom: rawWidth, left: rawWidth, unit: "px" }
                : { ...DEFAULT_WIDTH, ...rawWidth };

    return {
        ...DEFAULT_SIDE_STATE,
        ...(raw || {}),
        width,
        radius: { ...DEFAULT_RADIUS, ...((raw || {}).radius || {}) },
    };
}

function normalizeValue(value: any) {
    if (value && value.normal === undefined) {
        // Legacy flat format
        return {
            normal: normalizeSide(value),
            hover: { ...DEFAULT_SIDE_STATE },
            boxShadow: DEFAULT_BOX_SHADOW,
            transition: 300,
        };
    }
    return {
        normal: normalizeSide(value?.normal),
        hover: normalizeSide(value?.hover),
        boxShadow: { ...DEFAULT_BOX_SHADOW, ...(value?.boxShadow || {}) },
        transition: value?.transition ?? 300,
    };
}

// ─── BorderFields ─────────────────────────────────────────────────────────────

function BorderFields({
    current,
    data,
    onChange,
    tab,
}: {
    current: ReturnType<typeof normalizeSide>;
    data: ReturnType<typeof normalizeValue>;
    onChange: (v: any) => void;
    tab: "normal" | "hover";
}) {
    const update = (field: string, v: any) =>
        onChange({ ...data, [tab]: { ...current, [field]: v } });

    const hasActiveBorder = current.type !== "" && current.type !== "none";

    return (
        <div className="space-y-4">
            {/* Border Type */}
            <Select
                label="Border Type"
                value={current.type}
                onChange={(v) => update("type", v)}
                options={BORDER_TYPES}
                grid={2}
            />

            {hasActiveBorder && (
                <>
                    {/* Border Width — 4-sided */}
                    <Dimensions
                        type="padding"
                        label="Border Width"
                        units={WIDTH_UNITS}
                        value={current.width}
                        onChange={(v) => update("width", v)}
                    />

                    {/* Border Color */}
                    <ColorPickerPopup
                        label="Border Color"
                        value={current.color}
                        onChange={(c) => update("color", c)}
                    />
                </>
            )}

            {/* Border Radius — 4-sided */}
            <Dimensions
                type="padding"
                label="Border Radius"
                units={RADIUS_UNITS}
                value={current.radius}
                onChange={(v) => update("radius", v)}
            />

            {/* Transition Duration — Hover tab only */}
            {tab === "hover" && (
                <div className="pt-3 border-t border-gray-100">
                    <NumberControl
                        label="Transition Duration"
                        unit="ms"
                        value={data.transition}
                        onChange={(v) => onChange({ ...data, transition: v })}
                        min={0}
                        max={2000}
                        step={50}
                    />
                </div>
            )}
        </div>
    );
}

// ─── main component ───────────────────────────────────────────────────────────

export default function Border({ value, onChange }: any) {
    const [shadowOpen, setShadowOpen] = useState(false);

    const data = normalizeValue(value);

    return (
        <div className="space-y-3">
            {/* ── Normal / Hover tabs ── */}
            <Tabs
                tabs={[
                    {
                        label: "Normal",
                        content: (
                            <BorderFields
                                current={data.normal}
                                data={data}
                                onChange={onChange}
                                tab="normal"
                            />
                        ),
                    },
                    {
                        label: "Hover",
                        content: (
                            <BorderFields
                                current={data.hover}
                                data={data}
                                onChange={onChange}
                                tab="hover"
                            />
                        ),
                    },
                ]}
            />

            {/* ── Box Shadow (collapsible, outside tabs — has its own Normal/Hover) ── */}
            <div>
                <div className="flex items-center justify-between">
                    <span className="text-[13px] text-gray-700">Box Shadow</span>
                    <div className="flex items-center gap-1">
                        {/* Reset */}
                        <button
                            type="button"
                            onClick={() => onChange({ ...data, boxShadow: DEFAULT_BOX_SHADOW })}
                            className="flex items-center justify-center w-7 h-7 border border-gray-200 rounded bg-white text-gray-400 hover:bg-gray-50 cursor-pointer transition-colors"
                            title="Reset box shadow"
                        >
                            <Icon icon="mdi:refresh" width="13" />
                        </button>
                        {/* Edit toggle */}
                        <button
                            type="button"
                            onClick={() => setShadowOpen(!shadowOpen)}
                            className={`flex items-center justify-center w-7 h-7 border rounded cursor-pointer transition-colors ${shadowOpen
                                    ? "border-blue-300 bg-blue-50 text-blue-500"
                                    : "border-gray-200 bg-white text-gray-400 hover:bg-gray-50"
                                }`}
                            title={shadowOpen ? "Collapse" : "Edit box shadow"}
                        >
                            <Icon icon="solar:pen-bold" width="13" />
                        </button>
                    </div>
                </div>

                {shadowOpen && (
                    <div className="mt-3 pt-3 border-t border-gray-100">
                        <BoxShadow
                            value={data.boxShadow}
                            onChange={(v: any) => onChange({ ...data, boxShadow: v })}
                        />
                    </div>
                )}
            </div>
        </div>
    );
}
