import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/context/Provider";

export const metadata: Metadata = {
  title: "Next CMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
